#!/bin/sh
OMXPLAYER_LIBS="/usr/lib/omxplayer"
OMXPLAYER_DOCS="/usr/share/doc/omxplayer"

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -e "$OMXPLAYER_LIBS" ]; then
	rm -rf $OMXPLAYER_LIBS
    fi
    
    if [ -e "$OMXPLAYER_DOCS" ]; then
	rm -rf $OMXPLAYER_DOCS
    fi
fi
